spring:
  application:
    name: study
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:6343/single_sign_on_db
    username: daesoo
    password: daesoo123
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
#      url: jdbc:redis://유저네임:비밀번호@호스트 이름:포트번호
#      password: 비밀번호